import assert from "node:assert/strict";
import fs from "node:fs/promises";
import test from "node:test";

const sourcePath = new URL("../src/main.jsx", import.meta.url);

test("admin page keeps modal daily entry and confirmed summary modules", async () => {
  const source = await fs.readFile(sourcePath, "utf8");

  assert.match(source, /每日账户录入/);
  assert.match(source, /DailySnapshotModal/);
  assert.match(source, /import \{ calculateAll \} from "\.\/shared\/calculations\.js";/);
  assert.match(source, /const rows = useMemo\(\(\) => data \? calculateAll\(data\)\.summary : \[\], \[data\]\)/);
  assert.match(source, /syncFigure2InputsFromDailySnapshot/);
  assert.match(source, /upsertDailyBalance/);
  assert.match(source, /data\.assetSnapshots\.usStock\.floatingPnlJpy = rate/);
  assert.match(source, /import \{ inputNumberValue, isDecimalInputText \} from "\.\/shared\/formInputValues\.js";/);
  assert.match(source, /import \{ updateDailySnapshotDraftField \} from "\.\/shared\/dailySnapshotDrafts\.js";/);
  assert.match(source, /if \(!isDecimalInputText\(value\)\)/);
  assert.match(source, /A股当前总资产 CNY（核对用）/);
  assert.match(source, /JPY\/CNY 汇率/);
  assert.match(source, /updateDailySnapshotDraftField\(current, assetKey, field, value\)/);
  assert.match(source, /openDailySnapshotModal/);
  assert.match(source, /onClick=\{\(\) => openDailySnapshotModal\("new"\)\}>新增日期<\/button>/);
  assert.match(source, /saveDailySnapshotModal/);
  assert.match(source, /新增每日账户记录/);
  assert.match(source, /A股调仓后留存成本 CNY/);
  assert.match(source, /美股当前总资产 JPY/);
  assert.match(source, /查看/);
  assert.match(source, /编辑/);
  assert.match(source, /删除/);
  assert.match(source, /buildFixedAllocationRows/);
  assert.match(source, /fixedAllocationRows/);
  assert.match(source, /latestAccountRow/);
  assert.match(source, /账户资产总览/);
  assert.match(source, /A股总资产 CNY/);
  assert.match(source, /A股当日盈亏 CNY/);
  assert.match(source, /美股总资产 JPY/);
  assert.match(source, /美股总资产 CNY/);
  assert.match(source, /美股当日盈亏 CNY/);
  assert.doesNotMatch(source, /成员收益汇总/);
  assert.doesNotMatch(source, /成员盈亏汇总/);
  assert.doesNotMatch(source, /成员每日明细/);
  assert.doesNotMatch(source, /累计净入金/);
  assert.doesNotMatch(source, /当前分摊资产/);
  assert.doesNotMatch(source, /dailySummaryRows/);
  assert.doesNotMatch(source, /onClick=\{addDailySnapshot\}/);
  assert.doesNotMatch(source, /next\.dailySnapshots\.push/);
  assert.doesNotMatch(source, /className="wide-table"/);
  assert.doesNotMatch(source, /allocation-bar/);
  assert.doesNotMatch(source, /\["assetSnapshots", "usStock", "earlyRealizedOwnerId"\]/);
  assert.doesNotMatch(source, /calculations\?\.summary/);
});

test("user page renders liquid glass investment dashboard with history chart controls", async () => {
  const source = await fs.readFile(sourcePath, "utf8");

  assert.match(source, /from "recharts";/);
  assert.match(source, /function InvestmentDashboard\(\{ person, onLogout, onChangePassword \}\)/);
  assert.match(source, /function GlassHeader\(\{ person, onLogout, onChangePassword \}\)/);
  assert.match(source, /function ChangePasswordModal\(\{ token, onClose, onChanged \}\)/);
  assert.match(source, /apiPath\("\/api\/user\/password"\)/);
  assert.match(source, /修改密码/);
  assert.match(source, /保存新密码/);
  assert.match(source, /function MetricCard\(\{ label, value, change, tone = "neutral" \}\)/);
  assert.match(source, /function RangeSelector\(\{ value, onChange \}\)/);
  assert.match(source, /function HistoryChart\(\{ summary \}\)/);
  assert.match(source, /function GlassNotice\(\)/);
  assert.match(source, /const dashboardSummary = \{/);
  assert.match(source, /const historyData = useMemo\(\(\) => generateHistoryData\(summary\), \[summary\]\);/);
  assert.match(source, /principal: numberOrZero\(person\?\.capital\)/);
  assert.match(source, /totalProfitLoss: numberOrZero\(person\?\.totalProfit\)/);
  assert.match(source, /totalReturnRate: numberOrZero\(person\?\.returnRate\) \* 100/);
  assert.match(source, /const rangeOptions = \["7D", "30D", "90D", "1Y", "ALL"\];/);
  assert.match(source, /const \[range, setRange\] = useState\("30D"\);/);
  assert.match(source, /const \[mode, setMode\] = useState\("returnRate"\);/);
  assert.match(source, /<input type="date" value=\{startDate\}/);
  assert.match(source, /<input type="date" value=\{endDate\}/);
  assert.match(source, /投资收益总览/);
  assert.match(source, /本金 CNY/);
  assert.match(source, /总盈亏 CNY/);
  assert.match(source, /累计收益率/);
  assert.match(source, /历史收益率/);
  assert.match(source, /开始日期/);
  assert.match(source, /结束日期/);
  assert.match(source, /<InvestmentDashboard\s+person=\{person\}\s+onLogout=\{onLogout\}\s+onChangePassword=\{\(\) => setIsPasswordModalOpen\(true\)\}\s+\/>/);
  assert.doesNotMatch(source, /function UserSummaryTable/);
  assert.doesNotMatch(source, /<UserSummaryTable/);
});
